# a-discord-bot
# a discord bot dashboard website which has invite and support links and all bot features list
# This file was auto-generated by CodeForge AI

from app import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self):
        return f'<User {self.username}>'
